spring:
  profiles:
    active: ${ACTIVE_PROFILE}
---

spring:
  profiles: local
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform:
    url: ${JAWSDB_URL}

---
spring:
  profiles: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform:
    url: ${JAWSDB_URL}